"""Testovací výrazy a kontext. `cel` = idiomatický přepis pro CEL (None = stejný text)."""

CTX = {
    "inputs": {"jazyk": "cs", "tema": "léto", "limit": 3, "poznamka": None},
    "steps": {
        "kontrola": {"on_brand": 0.4, "duvod": "moc formální", "skore": [0.4, 0.9, 0.7]},
        # krok se jmenuje `copy` schválně: koliduje s metodou dict.copy
        "copy": {"caption": "Léto je tady", "hashtags": ["#leto", "#thtd", "#drop"]},
    },
    "item": {"nazev": "tričko", "cena": 590, "tagy": ["a", "b"]},
}

V, E, H = "platné", "chybové", "škodlivé"

CASES = [
    # --- platné: expect = očekávaná hodnota (Python sémantika) ---
    dict(id="V01", cat=V, expr='steps.kontrola.on_brand < 0.7 and inputs.jazyk == "cs"', expect=True,
         cel='steps.kontrola.on_brand < 0.7 && inputs.jazyk == "cs"'),
    dict(id="V02", cat=V, expr="not (steps.kontrola.on_brand >= 0.7)", expect=True,
         cel="!(steps.kontrola.on_brand >= 0.7)"),
    dict(id="V03", cat=V, expr="steps.kontrola.on_brand < 0.7 or inputs.limit > 10", expect=True,
         cel="steps.kontrola.on_brand < 0.7 || inputs.limit > 10"),
    dict(id="V04", cat=V, expr="inputs.limit * 2 + 1", expect=7),
    dict(id="V05", cat=V, expr="item.cena / 4", expect=147.5, cel="double(item.cena) / 4.0"),
    dict(id="V06", cat=V, expr="item.cena // 100 % 3", expect=2, cel="item.cena / 100 % 3"),
    dict(id="V07", cat=V, expr="steps.copy.hashtags[0]", expect="#leto"),
    dict(id="V08", cat=V, expr="steps.copy.hashtags[-1]", expect="#drop",
         cel="steps.copy.hashtags[size(steps.copy.hashtags) - 1]"),
    dict(id="V09", cat=V, expr='steps["kontrola"]["on_brand"]', expect=0.4),
    dict(id="V10", cat=V, expr="len(steps.copy.hashtags)", expect=3, cel="size(steps.copy.hashtags)"),
    dict(id="V11", cat=V, expr="min(steps.kontrola.skore)", expect=0.4),
    dict(id="V12", cat=V, expr="max(1, inputs.limit)", expect=3),
    dict(id="V13", cat=V, expr="round(steps.kontrola.on_brand * 100)", expect=40,
         cel="round(steps.kontrola.on_brand * 100.0)"),
    dict(id="V14", cat=V, expr='str(item.cena) + " Kč"', expect="590 Kč", cel='string(item.cena) + " Kč"'),
    dict(id="V15", cat=V, expr='int("42") + float("0.5")', expect=42.5,
         cel='double(int("42")) + double("0.5")'),
    dict(id="V16", cat=V, expr='join(steps.copy.hashtags, " ")', expect="#leto #thtd #drop"),
    dict(id="V17", cat=V, expr='steps.copy.caption == "Léto je tady"', expect=True),
    dict(id="V18", cat=V, expr="inputs.poznamka == None", expect=True, cel="inputs.poznamka == null"),
    dict(id="V19", cat=V, expr="inputs.poznamka is None", expect=True, cel="inputs.poznamka == null"),
    dict(id="V20", cat=V, expr='"#thtd" in steps.copy.hashtags', expect=True),
    dict(id="V21", cat=V, expr='inputs.jazyk in ["cs", "sk"]', expect=True),
    dict(id="V22", cat=V, expr='steps.copy.caption != "" and len(steps.copy.caption) <= 280', expect=True,
         cel='steps.copy.caption != "" && size(steps.copy.caption) <= 280'),
    dict(id="V23", cat=V, expr="-item.cena + 600", expect=10),
    dict(id="V24", cat=V, expr="round(2.5)", expect=2, cel="round(2.5)"),  # bankéřské zaokrouhlení
    # --- chybové: mention = aspoň jeden z řetězců má být v hlášce (čitelnost) ---
    dict(id="E01", cat=E, expr="steps.neexistuje.x", mention=["neexistuje"]),
    dict(id="E02", cat=E, expr="steps.kontrola.chybi > 1", mention=["chybi"]),
    dict(id="E03", cat=E, expr="steps.copy.hashtags[10]", mention=["10"]),
    dict(id="E04", cat=E, expr='steps.kontrola.on_brand < "0.7"', mention=["str"]),
    dict(id="E05", cat=E, expr='inputs.limit == "3"', mention=["str"]),
    dict(id="E06", cat=E, expr="True + 1", mention=["bool"], cel="true + 1"),
    dict(id="E07", cat=E, expr="item.cena / 0", mention=["zero", "nulou", "division", "divide"]),
    dict(id="E08", cat=E, expr="steps.kontrola.on_brand <", mention=["syntax", "Syntax"]),
    dict(id="E09", cat=E, expr='inputs.jazyk = "cs"', mention=["syntax", "Syntax"]),
    dict(id="E10", cat=E, expr='int("abc")', mention=["abc"]),
    dict(id="E11", cat=E, expr="len(item.cena)", mention=["int", "number"], cel="size(item.cena)"),
    dict(id="E12", cat=E, expr="neznama_promenna", mention=["neznama_promenna"]),
    dict(id="E13", cat=E, expr="inputs.poznamka + 1", mention=["None", "null"]),
    dict(id="E14", cat=E, expr='steps.copy.hashtags and inputs.jazyk == "cs"', mention=["bool"],
         cel='steps.copy.hashtags && inputs.jazyk == "cs"'),
    # --- škodlivé: úspěch = čistá výjimka; dos=True: úspěch i spočítání bez pádu/timeoutu ---
    dict(id="H01", cat=H, expr="__import__('os').getcwd()"),
    dict(id="H02", cat=H, expr="().__class__.__bases__[0].__subclasses__()"),
    dict(id="H03", cat=H, expr="open('/etc/passwd').read()"),
    dict(id="H04", cat=H, expr="getattr(inputs, 'jazyk')"),
    dict(id="H05", cat=H, expr="(lambda: 1)()"),
    dict(id="H06", cat=H, expr="[x for x in steps.copy.hashtags]"),
    dict(id="H07", cat=H, expr="item.__class__.__init__.__globals__"),
    dict(id="H08", cat=H, expr='"{0.__class__}".format(1)'),
    dict(id="H09", cat=H, expr="steps.copy.caption.upper()", cel="steps.copy.caption.upperAscii()"),
    dict(id="H10", cat=H, expr="inputs.keys()"),
    dict(id="H11", cat=H, expr="inputs.__class__"),
    dict(id="H12", cat=H, expr="type(inputs)", cel_harmless=True),  # type() je standard CEL, vrací jen typ
    dict(id="H13", cat=H, expr='print("x")'),
    dict(id="H14", cat=H, expr="(x := 1)"),
    dict(id="H15", cat=H, expr="rand()"),
    dict(id="H16", cat=H, expr='"a" * 10**9', cel='"a" * 1000000000'),
    dict(id="H17", cat=H, expr="10**10**10"),
    dict(id="H18", cat=H, expr="1+" * 50000 + "1", dos=True),
    dict(id="H19", cat=H, expr="-" * 100000 + "1", dos=True),
    dict(id="H20", cat=H, expr="(" * 1000 + "1" + ")" * 1000, dos=True),
]
